const APPLICATION_STATUSES = Object.freeze({
    NOT_SUBMITTED: 'NOT_SUBMITTED',
    SUBMITTED: 'SUBMITTED',
    UNDER_REVIEW: 'UNDER_REVIEW',
    MORE_INFORMATION_REQUIRED: 'MORE_INFORMATION_REQUIRED',
    SANDBOX_APPROVED: 'SANDBOX_APPROVED',
    SANDBOX_TESTING: 'SANDBOX_TESTING',
    PRODUCTION_REQUESTED: 'PRODUCTION_REQUESTED',
    PRODUCTION_UNDER_REVIEW: 'PRODUCTION_UNDER_REVIEW',
    LIVE_APPROVED: 'LIVE_APPROVED',
    REJECTED: 'REJECTED',
    SUSPENDED: 'SUSPENDED',
    REVOKED: 'REVOKED'
});

const ACCESS_LEVELS = Object.freeze({
    NONE: 'NONE',
    SANDBOX: 'SANDBOX',
    LIVE: 'LIVE'
});

const DEVELOPER_ACCOUNT_STATUSES = Object.freeze({
    PENDING_REVIEW: 'PENDING_REVIEW',
    ACTIVE: 'ACTIVE',
    SUSPENDED: 'SUSPENDED',
    REVOKED: 'REVOKED',
    REJECTED: 'REJECTED',
    MORE_INFORMATION_REQUIRED: 'MORE_INFORMATION_REQUIRED'
});

const DEVELOPER_ENVIRONMENTS = Object.freeze({
    SANDBOX: 'SANDBOX',
    LIVE: 'LIVE'
});

const CREDENTIAL_STATUSES = Object.freeze({
    ACTIVE: 'ACTIVE',
    SECONDARY: 'SECONDARY',
    EXPIRED: 'EXPIRED',
    REVOKED: 'REVOKED'
});

const SANDBOX_BOOKING_STATUSES = Object.freeze({
    CREATED: 'CREATED',
    VALIDATION_FAILED: 'VALIDATION_FAILED',
    RATE_LIMITED: 'RATE_LIMITED',
    WALLET_FAILED: 'WALLET_FAILED',
    BOOKED: 'BOOKED',
    PICKUP_SCHEDULED: 'PICKUP_SCHEDULED',
    PICKED_UP: 'PICKED_UP',
    IN_TRANSIT: 'IN_TRANSIT',
    OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
    DELIVERED: 'DELIVERED',
    PICKUP_FAILED: 'PICKUP_FAILED',
    DELIVERY_ATTEMPTED: 'DELIVERY_ATTEMPTED',
    RETURN_TO_ORIGIN: 'RETURN_TO_ORIGIN',
    CANCELLED: 'CANCELLED',
    REJECTED: 'REJECTED'
});

const SANDBOX_SCENARIOS = Object.freeze({
    SUCCESS: 'success',
    VALIDATION_ERROR: 'validation_error',
    INSUFFICIENT_SANDBOX_BALANCE: 'insufficient_sandbox_balance',
    CARRIER_TIMEOUT: 'carrier_timeout',
    BOOKING_REJECTED: 'booking_rejected',
    TRACKING_PROGRESS: 'tracking_progress',
    CANCELLATION_FAILURE: 'cancellation_failure'
});

const PARTNER_API_IDEMPOTENCY_STATUSES = Object.freeze({
    PROCESSING: 'PROCESSING',
    SUCCEEDED: 'SUCCEEDED',
    FAILED_RETRYABLE: 'FAILED_RETRYABLE',
    FAILED_FINAL: 'FAILED_FINAL',
    STATUS_UNKNOWN: 'STATUS_UNKNOWN'
});

const PARTNER_API_OPERATIONS = Object.freeze({
    CREATE_LIVE_BOOKING: 'CREATE_LIVE_BOOKING',
    CANCEL_LIVE_BOOKING: 'CANCEL_LIVE_BOOKING'
});

const PARTNER_API_CANCELLATION_STATUSES = Object.freeze({
    NOT_REQUESTED: 'NOT_REQUESTED',
    CANCELLATION_REQUESTED: 'CANCELLATION_REQUESTED',
    CANCELLATION_QUEUED: 'CANCELLATION_QUEUED',
    CANCELLATION_PROCESSING: 'CANCELLATION_PROCESSING',
    CANCELLATION_STATUS_UNKNOWN: 'CANCELLATION_STATUS_UNKNOWN',
    CANCELLED: 'CANCELLED',
    CANCELLATION_REJECTED: 'CANCELLATION_REJECTED',
    CANCELLATION_FAILED_RETRYABLE: 'CANCELLATION_FAILED_RETRYABLE',
    CANCELLATION_FAILED_FINAL: 'CANCELLATION_FAILED_FINAL',
    CANCELLATION_DEAD_LETTER: 'CANCELLATION_DEAD_LETTER',
    MANUAL_REVIEW_REQUIRED: 'MANUAL_REVIEW_REQUIRED'
});

const PARTNER_API_REFUND_STATUSES = Object.freeze({
    NOT_REQUIRED: 'NOT_REQUIRED',
    RESERVATION_RELEASE_PENDING: 'RESERVATION_RELEASE_PENDING',
    RESERVATION_RELEASED: 'RESERVATION_RELEASED',
    REFUND_PENDING: 'REFUND_PENDING',
    REFUND_PROCESSING: 'REFUND_PROCESSING',
    REFUNDED: 'REFUNDED',
    REFUND_FAILED_RETRYABLE: 'REFUND_FAILED_RETRYABLE',
    REFUND_FAILED_FINAL: 'REFUND_FAILED_FINAL',
    REFUND_RECONCILIATION_REQUIRED: 'REFUND_RECONCILIATION_REQUIRED'
});

const WALLET_RESERVATION_STATUSES = Object.freeze({
    ACTIVE: 'ACTIVE',
    SETTLED: 'SETTLED',
    RELEASED: 'RELEASED',
    EXPIRED: 'EXPIRED',
    RECONCILIATION_REQUIRED: 'RECONCILIATION_REQUIRED'
});

const PARTNER_API_OUTBOX_STATUSES = Object.freeze({
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    PUBLISHED: 'PUBLISHED',
    FAILED_RETRYABLE: 'FAILED_RETRYABLE',
    FAILED_FINAL: 'FAILED_FINAL'
});

const PARTNER_API_OUTBOX_EVENT_TYPES = Object.freeze({
    LIVE_PARTNER_BOOKING_REQUESTED: 'LIVE_PARTNER_BOOKING_REQUESTED',
    LIVE_PARTNER_BOOKING_CANCELLATION_REQUESTED: 'LIVE_PARTNER_BOOKING_CANCELLATION_REQUESTED'
});

const SHIPMENT_BOOKING_SOURCES = Object.freeze({
    CUSTOMER_DASHBOARD: 'CUSTOMER_DASHBOARD',
    PARTNER_API: 'PARTNER_API',
    ADMIN: 'ADMIN',
    BULK_UPLOAD: 'BULK_UPLOAD',
    PARTNER_PORTAL: 'PARTNER_PORTAL',
    WHATSAPP: 'WHATSAPP'
});

const PARTNER_API_PROCESSING_STATUSES = Object.freeze({
    PROCESSING: 'PROCESSING',
    SHIPMENT_PENDING: 'SHIPMENT_PENDING',
    OUTBOX_PENDING: 'OUTBOX_PENDING',
    QUEUED: 'QUEUED',
    CARRIER_REQUESTED: 'CARRIER_REQUESTED',
    CARRIER_STATUS_UNKNOWN: 'CARRIER_STATUS_UNKNOWN',
    PRICE_ADJUSTMENT_REQUIRED: 'PRICE_ADJUSTMENT_REQUIRED',
    WALLET_ADDITIONAL_FUNDS_REQUIRED: 'WALLET_ADDITIONAL_FUNDS_REQUIRED',
    WALLET_RECONCILIATION_REQUIRED: 'WALLET_RECONCILIATION_REQUIRED',
    BOOKED: 'BOOKED',
    LABEL_PENDING: 'LABEL_PENDING',
    LABEL_READY: 'LABEL_READY',
    LABEL_FAILED: 'LABEL_FAILED',
    FAILED_RETRYABLE: 'FAILED_RETRYABLE',
    FAILED_FINAL: 'FAILED_FINAL',
    DEAD_LETTER_RETRYABLE: 'DEAD_LETTER_RETRYABLE',
    DEAD_LETTER_MANUAL_REVIEW: 'DEAD_LETTER_MANUAL_REVIEW',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
});

const SLA_TIERS = Object.freeze({
    SILVER: 'SILVER',
    GOLD: 'GOLD',
    PLATINUM: 'PLATINUM'
});

const DEVELOPER_AUDIT_ACTOR_TYPES = Object.freeze({
    CUSTOMER: 'CUSTOMER',
    ADMIN: 'ADMIN',
    SYSTEM: 'SYSTEM',
    PARTNER_API: 'PARTNER_API'
});

const DEVELOPER_AUDIT_TARGET_TYPES = Object.freeze({
    DEVELOPER_ACCOUNT: 'DEVELOPER_ACCOUNT',
    DEVELOPER_APPLICATION: 'DEVELOPER_APPLICATION',
    API_CREDENTIAL: 'API_CREDENTIAL',
    API_REQUEST: 'API_REQUEST',
    SANDBOX_BOOKING: 'SANDBOX_BOOKING',
    PRODUCTION_REQUEST: 'PRODUCTION_REQUEST',
    CONFIGURATION: 'CONFIGURATION',
    WALLET: 'WALLET',
    BOOKING: 'BOOKING',
    SYSTEM: 'SYSTEM'
});

const DEVELOPER_PERMISSIONS = Object.freeze({
    OVERVIEW_READ: 'developer.overview.read',
    APPLICATIONS_READ: 'developer.applications.read',
    SANDBOX_APPROVE: 'developer.sandbox.approve',
    SANDBOX_REJECT: 'developer.sandbox.reject',
    ACCOUNTS_READ: 'developer.accounts.read',
    ACCOUNTS_STATUS_WRITE: 'developer.accounts.status.write',
    PRODUCTION_READ: 'developer.production.read',
    PRODUCTION_REVIEW: 'developer.production.review',
    PRODUCTION_APPROVE: 'developer.production.approve',
    PRODUCTION_REJECT: 'developer.production.reject',
    BOOKINGS_READ: 'developer.bookings.read',
    BOOKINGS_HOLD: 'developer.bookings.hold',
    RISK_READ: 'developer.risk.read',
    RISK_CLEAR: 'developer.risk.clear',
    COMPLIANCE_READ: 'developer.compliance.read',
    COMPLIANCE_VERIFY: 'developer.compliance.verify',
    CREDENTIALS_READ: 'developer.credentials.read',
    CREDENTIALS_REVOKE: 'developer.credentials.revoke',
    ANALYTICS_READ: 'developer.analytics.read',
    WALLETS_READ: 'developer.wallets.read',
    WALLETS_ADJUST: 'developer.wallets.adjust',
    SYSTEM_READ: 'developer.system.read',
    SYSTEM_RETRY: 'developer.system.retry',
    SYSTEM_RECOVERY: 'developer.system.recovery',
    AUDIT_READ: 'developer.audit.read',
    CONFIG_READ: 'developer.config.read',
    CONFIG_WRITE: 'developer.config.write',
    PERMISSIONS_READ: 'developer.permissions.read',
    PERMISSIONS_WRITE: 'developer.permissions.write'
});

const ACTIVE_APPLICATION_STATUSES = Object.freeze([
    APPLICATION_STATUSES.SUBMITTED,
    APPLICATION_STATUSES.UNDER_REVIEW,
    APPLICATION_STATUSES.MORE_INFORMATION_REQUIRED,
    APPLICATION_STATUSES.SANDBOX_APPROVED,
    APPLICATION_STATUSES.SANDBOX_TESTING,
    APPLICATION_STATUSES.PRODUCTION_REQUESTED,
    APPLICATION_STATUSES.PRODUCTION_UNDER_REVIEW,
    APPLICATION_STATUSES.LIVE_APPROVED
]);

const HTTP_METHODS = Object.freeze(['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']);

const APPLICATION_VOLUME_BUCKETS = Object.freeze(['< 100', '100 - 500', '500 - 2000', '2000+']);

const DEVELOPER_AUDIT_ACTIONS = Object.freeze({
    APPLICATION_SUBMITTED: 'DEVELOPER_APPLICATION_SUBMITTED',
    APPLICATION_UPDATED: 'DEVELOPER_APPLICATION_UPDATED',
    REVIEW_STARTED: 'DEVELOPER_APPLICATION_REVIEW_STARTED',
    REVIEWER_ASSIGNED: 'DEVELOPER_APPLICATION_REVIEWER_ASSIGNED',
    SANDBOX_APPROVED: 'DEVELOPER_SANDBOX_APPROVED',
    APPLICATION_REJECTED: 'DEVELOPER_APPLICATION_REJECTED',
    MORE_INFORMATION_REQUIRED: 'DEVELOPER_APPLICATION_MORE_INFORMATION_REQUIRED',
    CREDENTIAL_GENERATED: 'DEVELOPER_CREDENTIAL_GENERATED',
    CREDENTIAL_ROTATED: 'DEVELOPER_CREDENTIAL_ROTATED',
    CREDENTIAL_REVOKED: 'DEVELOPER_CREDENTIAL_REVOKED',
    CREDENTIAL_REAUTH_FAILED: 'DEVELOPER_CREDENTIAL_REAUTH_FAILED',
    CREDENTIAL_ADMIN_REVOKED: 'DEVELOPER_CREDENTIAL_ADMIN_REVOKED',
    CREDENTIAL_EXPIRED: 'DEVELOPER_CREDENTIAL_EXPIRED',
    API_KEY_AUTH_FAILED: 'DEVELOPER_API_KEY_AUTH_FAILED',
    API_KEY_AUTH_SUCCEEDED: 'DEVELOPER_API_KEY_AUTH_SUCCEEDED',
    SANDBOX_BOOKING_CREATED: 'DEVELOPER_SANDBOX_BOOKING_CREATED',
    SANDBOX_BOOKING_REJECTED: 'DEVELOPER_SANDBOX_BOOKING_REJECTED',
    SANDBOX_BOOKING_CANCELLED: 'DEVELOPER_SANDBOX_BOOKING_CANCELLED',
    SANDBOX_TRACKING_ACCESSED: 'DEVELOPER_SANDBOX_TRACKING_ACCESSED',
    SANDBOX_READINESS_UPDATED: 'DEVELOPER_SANDBOX_READINESS_UPDATED',
    SANDBOX_IDEMPOTENCY_CONFLICT: 'DEVELOPER_SANDBOX_IDEMPOTENCY_CONFLICT',
    SANDBOX_SCENARIO_EXECUTED: 'DEVELOPER_SANDBOX_SCENARIO_EXECUTED',
    PRODUCTION_ACCESS_REQUESTED: 'PRODUCTION_ACCESS_REQUESTED',
    PRODUCTION_REQUEST_UPDATED: 'PRODUCTION_REQUEST_UPDATED',
    PRODUCTION_REVIEW_STARTED: 'PRODUCTION_REVIEW_STARTED',
    PRODUCTION_REVIEWER_ASSIGNED: 'PRODUCTION_REVIEWER_ASSIGNED',
    PRODUCTION_MORE_INFORMATION_REQUIRED: 'PRODUCTION_MORE_INFORMATION_REQUIRED',
    PRODUCTION_REQUEST_REJECTED: 'PRODUCTION_REQUEST_REJECTED',
    PRODUCTION_ACCESS_APPROVED: 'PRODUCTION_ACCESS_APPROVED',
    LIVE_ACCESS_ENABLED: 'LIVE_ACCESS_ENABLED',
    LIVE_BOOKING_REQUESTED: 'LIVE_BOOKING_REQUESTED',
    LIVE_BOOKING_VALIDATED: 'LIVE_BOOKING_VALIDATED',
    LIVE_IDEMPOTENCY_CLAIMED: 'LIVE_IDEMPOTENCY_CLAIMED',
    LIVE_IDEMPOTENCY_CONFLICT: 'LIVE_IDEMPOTENCY_CONFLICT',
    LIVE_WALLET_FUNDS_RESERVED: 'LIVE_WALLET_FUNDS_RESERVED',
    LIVE_PENDING_SHIPMENT_CREATED: 'LIVE_PENDING_SHIPMENT_CREATED',
    LIVE_BOOKING_OUTBOX_CREATED: 'LIVE_BOOKING_OUTBOX_CREATED',
    LIVE_BOOKING_JOB_PUBLISHED: 'LIVE_BOOKING_JOB_PUBLISHED',
    LIVE_BOOKING_QUEUE_DEFERRED: 'LIVE_BOOKING_QUEUE_DEFERRED',
    LIVE_BOOKING_ADMISSION_FAILED: 'LIVE_BOOKING_ADMISSION_FAILED',
    LIVE_ORPHAN_ADMISSION_RECOVERED: 'LIVE_ORPHAN_ADMISSION_RECOVERED',
    LIVE_BOOKING_JOB_STARTED: 'LIVE_BOOKING_JOB_STARTED',
    LIVE_CARRIER_BOOKING_REQUESTED: 'LIVE_CARRIER_BOOKING_REQUESTED',
    LIVE_CARRIER_BOOKING_SUCCEEDED: 'LIVE_CARRIER_BOOKING_SUCCEEDED',
    LIVE_CARRIER_BOOKING_FAILED: 'LIVE_CARRIER_BOOKING_FAILED',
    LIVE_CARRIER_STATUS_UNKNOWN: 'LIVE_CARRIER_STATUS_UNKNOWN',
    LIVE_CARRIER_BOOKING_RECONCILED: 'LIVE_CARRIER_BOOKING_RECONCILED',
    LIVE_WALLET_DEBIT_COMPLETED: 'LIVE_WALLET_DEBIT_COMPLETED',
    LIVE_WALLET_UNUSED_RESERVATION_RELEASED: 'LIVE_WALLET_UNUSED_RESERVATION_RELEASED',
    LIVE_WALLET_ADDITIONAL_FUNDS_REQUIRED: 'LIVE_WALLET_ADDITIONAL_FUNDS_REQUIRED',
    LIVE_WALLET_RECONCILIATION_REQUIRED: 'LIVE_WALLET_RECONCILIATION_REQUIRED',
    LIVE_WALLET_RECONCILED: 'LIVE_WALLET_RECONCILED',
    LIVE_WALLET_RESERVATION_RELEASED: 'LIVE_WALLET_RESERVATION_RELEASED',
    LIVE_LABEL_GENERATED: 'LIVE_LABEL_GENERATED',
    LIVE_LABEL_FAILED: 'LIVE_LABEL_FAILED',
    LIVE_JOB_MOVED_TO_DEAD_LETTER: 'LIVE_JOB_MOVED_TO_DEAD_LETTER',
    LIVE_MANUAL_RECOVERY_REQUESTED: 'LIVE_MANUAL_RECOVERY_REQUESTED',
    LIVE_MANUAL_RECOVERY_COMPLETED: 'LIVE_MANUAL_RECOVERY_COMPLETED',
    LIVE_CANCELLATION_REQUESTED: 'LIVE_CANCELLATION_REQUESTED',
    LIVE_CANCELLATION_VALIDATED: 'LIVE_CANCELLATION_VALIDATED',
    LIVE_CANCELLATION_IDEMPOTENCY_CLAIMED: 'LIVE_CANCELLATION_IDEMPOTENCY_CLAIMED',
    LIVE_CANCELLATION_QUEUED: 'LIVE_CANCELLATION_QUEUED',
    LIVE_CANCELLATION_PROCESSING: 'LIVE_CANCELLATION_PROCESSING',
    LIVE_CARRIER_CANCELLATION_REQUESTED: 'LIVE_CARRIER_CANCELLATION_REQUESTED',
    LIVE_CARRIER_CANCELLATION_CONFIRMED: 'LIVE_CARRIER_CANCELLATION_CONFIRMED',
    LIVE_CARRIER_CANCELLATION_REJECTED: 'LIVE_CARRIER_CANCELLATION_REJECTED',
    LIVE_CANCELLATION_STATUS_UNKNOWN: 'LIVE_CANCELLATION_STATUS_UNKNOWN',
    LIVE_RESERVATION_RELEASED: 'LIVE_RESERVATION_RELEASED',
    LIVE_REFUND_REQUESTED: 'LIVE_REFUND_REQUESTED',
    LIVE_REFUND_COMPLETED: 'LIVE_REFUND_COMPLETED',
    LIVE_REFUND_RECONCILIATION_REQUIRED: 'LIVE_REFUND_RECONCILIATION_REQUIRED',
    LIVE_CANCELLATION_DEAD_LETTERED: 'LIVE_CANCELLATION_DEAD_LETTERED',
    LIVE_CANCELLATION_MANUAL_RECOVERY: 'LIVE_CANCELLATION_MANUAL_RECOVERY'
});

const DEVELOPER_ERROR_CODES = Object.freeze({
    AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
    API_KEY_REQUIRED: 'API_KEY_REQUIRED',
    INVALID_API_KEY: 'INVALID_API_KEY',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
    APPLICATION_ALREADY_EXISTS: 'APPLICATION_ALREADY_EXISTS',
    INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
    INVALID_INPUT: 'INVALID_INPUT',
    MANDATORY_AGREEMENT_REQUIRED: 'MANDATORY_AGREEMENT_REQUIRED',
    CUSTOMER_ACCOUNT_RESTRICTED: 'CUSTOMER_ACCOUNT_RESTRICTED',
    SANDBOX_ALREADY_APPROVED: 'SANDBOX_ALREADY_APPROVED',
    RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
    CREDENTIAL_NOT_FOUND: 'CREDENTIAL_NOT_FOUND',
    CREDENTIAL_LIMIT_REACHED: 'CREDENTIAL_LIMIT_REACHED',
    CREDENTIAL_ALREADY_REVOKED: 'CREDENTIAL_ALREADY_REVOKED',
    CREDENTIAL_REVOKED: 'CREDENTIAL_REVOKED',
    CREDENTIAL_EXPIRED: 'CREDENTIAL_EXPIRED',
    CREDENTIAL_ROTATION_CONFLICT: 'CREDENTIAL_ROTATION_CONFLICT',
    REAUTHENTICATION_REQUIRED: 'REAUTHENTICATION_REQUIRED',
    REAUTHENTICATION_FAILED: 'REAUTHENTICATION_FAILED',
    CREDENTIAL_ACTION_RATE_LIMITED: 'CREDENTIAL_ACTION_RATE_LIMITED',
    ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
    ACCESS_NOT_ENABLED: 'ACCESS_NOT_ENABLED',
    LIVE_ACCESS_REQUIRED: 'LIVE_ACCESS_REQUIRED',
    ENVIRONMENT_NOT_ALLOWED: 'ENVIRONMENT_NOT_ALLOWED',
    FEATURE_NOT_IMPLEMENTED: 'FEATURE_NOT_IMPLEMENTED',
    PARTNER_REQUEST_ID_REQUIRED: 'PARTNER_REQUEST_ID_REQUIRED',
    INVALID_PARTNER_REQUEST_ID: 'INVALID_PARTNER_REQUEST_ID',
    DUPLICATE_PARTNER_REQUEST: 'DUPLICATE_PARTNER_REQUEST',
    IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
    INVALID_SANDBOX_SCENARIO: 'INVALID_SANDBOX_SCENARIO',
    SANDBOX_BOOKING_NOT_FOUND: 'SANDBOX_BOOKING_NOT_FOUND',
    SANDBOX_TRACKING_NOT_FOUND: 'SANDBOX_TRACKING_NOT_FOUND',
    BOOKING_NOT_CANCELLABLE: 'BOOKING_NOT_CANCELLABLE',
    INVALID_BOOKING_STATUS_TRANSITION: 'INVALID_BOOKING_STATUS_TRANSITION',
    SANDBOX_INSUFFICIENT_BALANCE: 'SANDBOX_INSUFFICIENT_BALANCE',
    SANDBOX_BOOKING_REJECTED: 'SANDBOX_BOOKING_REJECTED',
    SANDBOX_CARRIER_TIMEOUT: 'SANDBOX_CARRIER_TIMEOUT',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    PRODUCTION_NOT_ELIGIBLE: 'PRODUCTION_NOT_ELIGIBLE',
    PRODUCTION_READINESS_INCOMPLETE: 'PRODUCTION_READINESS_INCOMPLETE',
    SANDBOX_ACCESS_REQUIRED: 'SANDBOX_ACCESS_REQUIRED',
    SANDBOX_TESTS_INCOMPLETE: 'SANDBOX_TESTS_INCOMPLETE',
    KYC_APPROVAL_REQUIRED: 'KYC_APPROVAL_REQUIRED',
    PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
    WALLET_NOT_READY: 'WALLET_NOT_READY',
    COMPLIANCE_BLOCKED: 'COMPLIANCE_BLOCKED',
    SECURITY_RESTRICTION: 'SECURITY_RESTRICTION',
    PRODUCTION_REQUEST_ALREADY_EXISTS: 'PRODUCTION_REQUEST_ALREADY_EXISTS',
    PRODUCTION_REQUEST_NOT_FOUND: 'PRODUCTION_REQUEST_NOT_FOUND',
    PRODUCTION_REQUEST_NOT_REVIEWABLE: 'PRODUCTION_REQUEST_NOT_REVIEWABLE',
    PRODUCTION_APPROVAL_CONFLICT: 'PRODUCTION_APPROVAL_CONFLICT',
    MORE_INFORMATION_REQUIRED: 'MORE_INFORMATION_REQUIRED',
    PRODUCTION_ALREADY_APPROVED: 'PRODUCTION_ALREADY_APPROVED',
    PRODUCTION_APPROVAL_PERMISSION_REQUIRED: 'PRODUCTION_APPROVAL_PERMISSION_REQUIRED',
    LIVE_API_NOT_IMPLEMENTED: 'LIVE_API_NOT_IMPLEMENTED',
    REQUEST_PROCESSING: 'REQUEST_PROCESSING',
    INSUFFICIENT_WALLET_BALANCE: 'INSUFFICIENT_WALLET_BALANCE',
    WALLET_RESERVATION_FAILED: 'WALLET_RESERVATION_FAILED',
    SERVICE_NOT_AVAILABLE: 'SERVICE_NOT_AVAILABLE',
    PRICING_UNAVAILABLE: 'PRICING_UNAVAILABLE',
    QUEUE_UNAVAILABLE: 'QUEUE_UNAVAILABLE',
    QUEUE_BACKPRESSURE: 'QUEUE_BACKPRESSURE',
    SERVICE_TEMPORARILY_UNAVAILABLE: 'SERVICE_TEMPORARILY_UNAVAILABLE',
    BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
    TRACKING_NOT_FOUND: 'TRACKING_NOT_FOUND',
    LABEL_NOT_AVAILABLE: 'LABEL_NOT_AVAILABLE',
    CANCELLATION_NOT_ALLOWED: 'CANCELLATION_NOT_ALLOWED',
    CANCELLATION_NOT_FOUND: 'CANCELLATION_NOT_FOUND',
    MANUAL_RECOVERY_NOT_ALLOWED: 'MANUAL_RECOVERY_NOT_ALLOWED',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
});

const values = (obj) => Object.freeze(Object.values(obj));

module.exports = {
    APPLICATION_STATUSES,
    APPLICATION_STATUS_VALUES: values(APPLICATION_STATUSES),
    ACTIVE_APPLICATION_STATUSES,
    ACCESS_LEVELS,
    ACCESS_LEVEL_VALUES: values(ACCESS_LEVELS),
    DEVELOPER_ACCOUNT_STATUSES,
    DEVELOPER_ACCOUNT_STATUS_VALUES: values(DEVELOPER_ACCOUNT_STATUSES),
    DEVELOPER_ENVIRONMENTS,
    DEVELOPER_ENVIRONMENT_VALUES: values(DEVELOPER_ENVIRONMENTS),
    CREDENTIAL_STATUSES,
    CREDENTIAL_STATUS_VALUES: values(CREDENTIAL_STATUSES),
    SANDBOX_BOOKING_STATUSES,
    SANDBOX_BOOKING_STATUS_VALUES: values(SANDBOX_BOOKING_STATUSES),
    SANDBOX_SCENARIOS,
    SANDBOX_SCENARIO_VALUES: values(SANDBOX_SCENARIOS),
    PARTNER_API_IDEMPOTENCY_STATUSES,
    PARTNER_API_IDEMPOTENCY_STATUS_VALUES: values(PARTNER_API_IDEMPOTENCY_STATUSES),
    PARTNER_API_OPERATIONS,
    PARTNER_API_OPERATION_VALUES: values(PARTNER_API_OPERATIONS),
    PARTNER_API_CANCELLATION_STATUSES,
    PARTNER_API_CANCELLATION_STATUS_VALUES: values(PARTNER_API_CANCELLATION_STATUSES),
    PARTNER_API_REFUND_STATUSES,
    PARTNER_API_REFUND_STATUS_VALUES: values(PARTNER_API_REFUND_STATUSES),
    WALLET_RESERVATION_STATUSES,
    WALLET_RESERVATION_STATUS_VALUES: values(WALLET_RESERVATION_STATUSES),
    PARTNER_API_OUTBOX_STATUSES,
    PARTNER_API_OUTBOX_STATUS_VALUES: values(PARTNER_API_OUTBOX_STATUSES),
    PARTNER_API_OUTBOX_EVENT_TYPES,
    PARTNER_API_OUTBOX_EVENT_TYPE_VALUES: values(PARTNER_API_OUTBOX_EVENT_TYPES),
    SHIPMENT_BOOKING_SOURCES,
    SHIPMENT_BOOKING_SOURCE_VALUES: values(SHIPMENT_BOOKING_SOURCES),
    PARTNER_API_PROCESSING_STATUSES,
    PARTNER_API_PROCESSING_STATUS_VALUES: values(PARTNER_API_PROCESSING_STATUSES),
    SLA_TIERS,
    SLA_TIER_VALUES: values(SLA_TIERS),
    DEVELOPER_AUDIT_ACTOR_TYPES,
    DEVELOPER_AUDIT_ACTOR_TYPE_VALUES: values(DEVELOPER_AUDIT_ACTOR_TYPES),
    DEVELOPER_AUDIT_TARGET_TYPES,
    DEVELOPER_AUDIT_TARGET_TYPE_VALUES: values(DEVELOPER_AUDIT_TARGET_TYPES),
    DEVELOPER_PERMISSIONS,
    DEVELOPER_PERMISSION_VALUES: values(DEVELOPER_PERMISSIONS),
    HTTP_METHODS,
    APPLICATION_VOLUME_BUCKETS,
    DEVELOPER_AUDIT_ACTIONS,
    DEVELOPER_AUDIT_ACTION_VALUES: values(DEVELOPER_AUDIT_ACTIONS),
    DEVELOPER_ERROR_CODES,
    DEVELOPER_ERROR_CODE_VALUES: values(DEVELOPER_ERROR_CODES)
};
