const { APPLICATION_STATUSES, DEVELOPER_ERROR_CODES } = require('../../constants/developerPortal');
const { DeveloperPortalError } = require('../../utils/developerPortalErrors');

const ALLOWED_TRANSITIONS = Object.freeze({
    [APPLICATION_STATUSES.NOT_SUBMITTED]: [APPLICATION_STATUSES.SUBMITTED],
    [APPLICATION_STATUSES.SUBMITTED]: [
        APPLICATION_STATUSES.UNDER_REVIEW,
        APPLICATION_STATUSES.SANDBOX_APPROVED,
        APPLICATION_STATUSES.MORE_INFORMATION_REQUIRED,
        APPLICATION_STATUSES.REJECTED
    ],
    [APPLICATION_STATUSES.UNDER_REVIEW]: [
        APPLICATION_STATUSES.SANDBOX_APPROVED,
        APPLICATION_STATUSES.MORE_INFORMATION_REQUIRED,
        APPLICATION_STATUSES.REJECTED
    ],
    [APPLICATION_STATUSES.MORE_INFORMATION_REQUIRED]: [APPLICATION_STATUSES.SUBMITTED],
    [APPLICATION_STATUSES.SANDBOX_APPROVED]: [APPLICATION_STATUSES.SANDBOX_TESTING]
});

const ALLOWED_PRODUCTION_TRANSITIONS = Object.freeze({
    [APPLICATION_STATUSES.SANDBOX_APPROVED]: [APPLICATION_STATUSES.PRODUCTION_REQUESTED],
    [APPLICATION_STATUSES.SANDBOX_TESTING]: [APPLICATION_STATUSES.PRODUCTION_REQUESTED],
    [APPLICATION_STATUSES.PRODUCTION_REQUESTED]: [
        APPLICATION_STATUSES.PRODUCTION_UNDER_REVIEW,
        APPLICATION_STATUSES.MORE_INFORMATION_REQUIRED,
        APPLICATION_STATUSES.REJECTED,
        APPLICATION_STATUSES.LIVE_APPROVED
    ],
    [APPLICATION_STATUSES.PRODUCTION_UNDER_REVIEW]: [
        APPLICATION_STATUSES.MORE_INFORMATION_REQUIRED,
        APPLICATION_STATUSES.REJECTED,
        APPLICATION_STATUSES.LIVE_APPROVED
    ],
    [APPLICATION_STATUSES.MORE_INFORMATION_REQUIRED]: [
        APPLICATION_STATUSES.PRODUCTION_REQUESTED,
        APPLICATION_STATUSES.PRODUCTION_UNDER_REVIEW
    ]
});

const assertApplicationTransition = (fromStatus, toStatus) => {
    const allowed = ALLOWED_TRANSITIONS[fromStatus] || [];
    if (!allowed.includes(toStatus)) {
        throw new DeveloperPortalError(
            DEVELOPER_ERROR_CODES.INVALID_STATUS_TRANSITION,
            `Application cannot transition from ${fromStatus} to ${toStatus}.`
        );
    }
};

const assertProductionRequestTransition = (fromStatus, toStatus) => {
    const allowed = ALLOWED_PRODUCTION_TRANSITIONS[fromStatus] || [];
    if (!allowed.includes(toStatus)) {
        throw new DeveloperPortalError(
            DEVELOPER_ERROR_CODES.INVALID_STATUS_TRANSITION,
            `Production request cannot transition from ${fromStatus} to ${toStatus}.`
        );
    }
};

module.exports = {
    ALLOWED_TRANSITIONS,
    ALLOWED_PRODUCTION_TRANSITIONS,
    assertApplicationTransition,
    assertProductionRequestTransition
};
