const { DEVELOPER_ERROR_CODES } = require('../constants/developerPortal');
const { makePublicId } = require('./developerPortalIds');

const DEFAULT_STATUS_BY_CODE = {
    [DEVELOPER_ERROR_CODES.AUTHENTICATION_REQUIRED]: 401,
    [DEVELOPER_ERROR_CODES.API_KEY_REQUIRED]: 401,
    [DEVELOPER_ERROR_CODES.INVALID_API_KEY]: 401,
    [DEVELOPER_ERROR_CODES.PERMISSION_DENIED]: 403,
    [DEVELOPER_ERROR_CODES.APPLICATION_NOT_FOUND]: 404,
    [DEVELOPER_ERROR_CODES.APPLICATION_ALREADY_EXISTS]: 409,
    [DEVELOPER_ERROR_CODES.INVALID_STATUS_TRANSITION]: 409,
    [DEVELOPER_ERROR_CODES.INVALID_INPUT]: 400,
    [DEVELOPER_ERROR_CODES.MANDATORY_AGREEMENT_REQUIRED]: 400,
    [DEVELOPER_ERROR_CODES.CUSTOMER_ACCOUNT_RESTRICTED]: 403,
    [DEVELOPER_ERROR_CODES.SANDBOX_ALREADY_APPROVED]: 409,
    [DEVELOPER_ERROR_CODES.RESOURCE_CONFLICT]: 409,
    [DEVELOPER_ERROR_CODES.CREDENTIAL_NOT_FOUND]: 404,
    [DEVELOPER_ERROR_CODES.CREDENTIAL_LIMIT_REACHED]: 409,
    [DEVELOPER_ERROR_CODES.CREDENTIAL_ALREADY_REVOKED]: 409,
    [DEVELOPER_ERROR_CODES.CREDENTIAL_REVOKED]: 401,
    [DEVELOPER_ERROR_CODES.CREDENTIAL_EXPIRED]: 401,
    [DEVELOPER_ERROR_CODES.CREDENTIAL_ROTATION_CONFLICT]: 409,
    [DEVELOPER_ERROR_CODES.REAUTHENTICATION_REQUIRED]: 401,
    [DEVELOPER_ERROR_CODES.REAUTHENTICATION_FAILED]: 401,
    [DEVELOPER_ERROR_CODES.CREDENTIAL_ACTION_RATE_LIMITED]: 429,
    [DEVELOPER_ERROR_CODES.ACCOUNT_SUSPENDED]: 403,
    [DEVELOPER_ERROR_CODES.ACCESS_NOT_ENABLED]: 403,
    [DEVELOPER_ERROR_CODES.LIVE_ACCESS_REQUIRED]: 403,
    [DEVELOPER_ERROR_CODES.ENVIRONMENT_NOT_ALLOWED]: 403,
    [DEVELOPER_ERROR_CODES.FEATURE_NOT_IMPLEMENTED]: 501,
    [DEVELOPER_ERROR_CODES.PARTNER_REQUEST_ID_REQUIRED]: 400,
    [DEVELOPER_ERROR_CODES.INVALID_PARTNER_REQUEST_ID]: 400,
    [DEVELOPER_ERROR_CODES.DUPLICATE_PARTNER_REQUEST]: 409,
    [DEVELOPER_ERROR_CODES.IDEMPOTENCY_CONFLICT]: 409,
    [DEVELOPER_ERROR_CODES.INVALID_SANDBOX_SCENARIO]: 400,
    [DEVELOPER_ERROR_CODES.SANDBOX_BOOKING_NOT_FOUND]: 404,
    [DEVELOPER_ERROR_CODES.SANDBOX_TRACKING_NOT_FOUND]: 404,
    [DEVELOPER_ERROR_CODES.BOOKING_NOT_CANCELLABLE]: 409,
    [DEVELOPER_ERROR_CODES.INVALID_BOOKING_STATUS_TRANSITION]: 409,
    [DEVELOPER_ERROR_CODES.SANDBOX_INSUFFICIENT_BALANCE]: 402,
    [DEVELOPER_ERROR_CODES.SANDBOX_BOOKING_REJECTED]: 422,
    [DEVELOPER_ERROR_CODES.SANDBOX_CARRIER_TIMEOUT]: 504,
    [DEVELOPER_ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
    [DEVELOPER_ERROR_CODES.PRODUCTION_NOT_ELIGIBLE]: 403,
    [DEVELOPER_ERROR_CODES.PRODUCTION_READINESS_INCOMPLETE]: 403,
    [DEVELOPER_ERROR_CODES.SANDBOX_ACCESS_REQUIRED]: 403,
    [DEVELOPER_ERROR_CODES.SANDBOX_TESTS_INCOMPLETE]: 403,
    [DEVELOPER_ERROR_CODES.KYC_APPROVAL_REQUIRED]: 403,
    [DEVELOPER_ERROR_CODES.PROFILE_INCOMPLETE]: 403,
    [DEVELOPER_ERROR_CODES.WALLET_NOT_READY]: 403,
    [DEVELOPER_ERROR_CODES.COMPLIANCE_BLOCKED]: 403,
    [DEVELOPER_ERROR_CODES.SECURITY_RESTRICTION]: 403,
    [DEVELOPER_ERROR_CODES.PRODUCTION_REQUEST_ALREADY_EXISTS]: 409,
    [DEVELOPER_ERROR_CODES.PRODUCTION_REQUEST_NOT_FOUND]: 404,
    [DEVELOPER_ERROR_CODES.PRODUCTION_REQUEST_NOT_REVIEWABLE]: 409,
    [DEVELOPER_ERROR_CODES.PRODUCTION_APPROVAL_CONFLICT]: 409,
    [DEVELOPER_ERROR_CODES.MORE_INFORMATION_REQUIRED]: 409,
    [DEVELOPER_ERROR_CODES.PRODUCTION_ALREADY_APPROVED]: 409,
    [DEVELOPER_ERROR_CODES.PRODUCTION_APPROVAL_PERMISSION_REQUIRED]: 403,
    [DEVELOPER_ERROR_CODES.LIVE_API_NOT_IMPLEMENTED]: 501,
    [DEVELOPER_ERROR_CODES.REQUEST_PROCESSING]: 202,
    [DEVELOPER_ERROR_CODES.INSUFFICIENT_WALLET_BALANCE]: 402,
    [DEVELOPER_ERROR_CODES.WALLET_RESERVATION_FAILED]: 409,
    [DEVELOPER_ERROR_CODES.SERVICE_NOT_AVAILABLE]: 422,
    [DEVELOPER_ERROR_CODES.PRICING_UNAVAILABLE]: 503,
    [DEVELOPER_ERROR_CODES.QUEUE_UNAVAILABLE]: 503,
    [DEVELOPER_ERROR_CODES.QUEUE_BACKPRESSURE]: 503,
    [DEVELOPER_ERROR_CODES.SERVICE_TEMPORARILY_UNAVAILABLE]: 503,
    [DEVELOPER_ERROR_CODES.BOOKING_NOT_FOUND]: 404,
    [DEVELOPER_ERROR_CODES.TRACKING_NOT_FOUND]: 404,
    [DEVELOPER_ERROR_CODES.LABEL_NOT_AVAILABLE]: 409,
    [DEVELOPER_ERROR_CODES.CANCELLATION_NOT_ALLOWED]: 409,
    [DEVELOPER_ERROR_CODES.CANCELLATION_NOT_FOUND]: 404,
    [DEVELOPER_ERROR_CODES.MANUAL_RECOVERY_NOT_ALLOWED]: 409,
    [DEVELOPER_ERROR_CODES.INTERNAL_ERROR]: 500
};

class DeveloperPortalError extends Error {
    constructor(code, message, details = null, statusCode = null) {
        super(message);
        this.name = 'DeveloperPortalError';
        this.code = code;
        this.statusCode = statusCode || DEFAULT_STATUS_BY_CODE[code] || 500;
        this.details = details;
    }
}

const makeRequestId = () => makePublicId('REQ');

const sendDeveloperError = (res, error, requestId = makeRequestId()) => {
    if (error instanceof DeveloperPortalError) {
        const response = {
            success: false,
            error_code: error.code,
            message: error.message,
            request_id: requestId
        };

        if (error.details && error.statusCode < 500) {
            response.details = error.details;
        }

        return res.status(error.statusCode).json(response);
    }

    console.error('Developer portal error:', error && error.message ? error.message : error);
    return res.status(500).json({
        success: false,
        error_code: 'INTERNAL_ERROR',
        message: 'An unexpected developer portal error occurred.',
        request_id: requestId
    });
};

const asyncDeveloperHandler = (handler) => async (req, res) => {
    const requestId = req.headers['x-request-id'] || makeRequestId();
    try {
        await handler(req, res, requestId);
    } catch (error) {
        sendDeveloperError(res, error, requestId);
    }
};

module.exports = {
    DeveloperPortalError,
    asyncDeveloperHandler,
    sendDeveloperError,
    makeRequestId
};
